code: DakaoCerN3
jrxml: DakaoCerN3.jrxml
defaultOutputName: dakao-certificate-n3
parameters:
  CerNo:
    path: cerNo
    type: string
  FullName:
    path: fullName
    type: string
  Gender:
    path: gender
    type: string
  Birthday:
    path: birthday
    type: string
  Nationality:
    path: nationality
    type: string
  IdentityCard:
    path: identityCard
    type: string
  Position:
    path: position
    type: string
  TrainingGroup:
    path: trainingGroup
    type: string
  Company:
    path: company
    type: string
  AvatarPath:
    path: avatarPath
    type: assetPath
  DateFrom:
    path: dateFrom
    type: string
  DateTo:
    path: dateTo
    type: string
  CerResult:
    path: cerResult
    type: string
  NumYear:
    path: numYear
    type: string
  ExpireFrom:
    path: expireFrom
    type: string
  ExpireTo:
    path: expireTo
    type: string
  CerName:
    path: cerName
    type: string
  ExpireFromDay:
    path: expireFromDay
    type: string
  ExpireFromMonth:
    path: expireFromMonth
    type: string
  ExpireFromYear:
    path: expireFromYear
    type: string
  ExpireToDay:
    path: expireToDay
    type: string
  ExpireToMonth:
    path: expireToMonth
    type: string
  ExpireToYear:
    path: expireToYear
    type: string
